name: Update gist with WakaTime stats
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js  --unhandled-rejections=strict
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 7ae722ce6a77f06b9c12f8d18c9a9e5b
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          