name: Update gist with WakaTime stats
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 996068b516e21decf4a0a39ff0c2fe39
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
